### PR TITLE
Added --dte option to option put and call methods

### PR DESCRIPTION
**Pull request by andywatts**
Added --dte to put/call methods

```
$ tt option call -d 20 --dte 3  --weeklies SPX 1
Quote for SPX 5815.0C 
      2024-10-11      
┏━━━━━━┳━━━━━━┳━━━━━━┓
┃ Bid  ┃ Mid  ┃ Ask  ┃
┡━━━━━━╇━━━━━━╇━━━━━━┩
│ 7.30 │ 7.50 │ 7.70 │
└──────┴──────┴──────┘
Please enter a limit price per quantity (default mid): 
```

### CODE REVIEW

**Comment by Graeme22** [comment]
This seems useful, thanks! Could you make it so that if `--dte` is passed, weeklies are implicitly included as well?

**Comment by Graeme22** [comment]
> This seems useful, thanks! Could you make it so that if `--dte` is passed, weeklies are implicitly included as well?

Also, I'll need to add some logic to handle the edge case where both weekly and monthly options are present for an expiration.

**Comment by andywatts** [comment]
> This seems useful, thanks! Could you make it so that if `--dte` is passed, weeklies are implicitly included as well?

Good idea.   Turns out it works this way already.
Here's with and without `--weeklies`

```
(tastytrade-cli) vscode ➜ /workspaces/tastytrade-cli (main) $ tt option call -d 20 --dte 3 SPX 1
Quote for SPX 5835.0C 
      2024-10-14      
┏━━━━━━┳━━━━━━┳━━━━━━┓
┃ Bid  ┃ Mid  ┃ Ask  ┃
┡━━━━━━╇━━━━━━╇━━━━━━┩
│ 6.60 │ 6.70 │ 6.80 │
└──────┴──────┴──────┘
Please enter a limit price per quantity (default mid): 


(tastytrade-cli) vscode ➜ /workspaces/tastytrade-cli (main) $ tt option call -d 20 --dte 3 --weeklies SPX 1
Quote for SPX 5835.0C 
      2024-10-14      
┏━━━━━━┳━━━━━━┳━━━━━━┓
┃ Bid  ┃ Mid  ┃ Ask  ┃
┡━━━━━━╇━━━━━━╇━━━━━━┩
│ 6.90 │ 7.00 │ 7.10 │
```

**Review by Graeme22 — APPROVED** [review]
Thanks!

**Comment by Graeme22** [comment]
> Good idea. Turns out it works this way already. Here's with and without `--weeklies`

Ha, such a good idea you already did it!

**Comment by andywatts** [comment]
> > This seems useful, thanks! Could you make it so that if `--dte` is passed, weeklies are implicitly included as well?
> 
> Also, I'll need to add some logic to handle the edge case where both weekly and monthly options are present for an expiration.

Good point.   I'm trying to find a date to test.
10/18 has AM settled and your lib is correctly ignoring it.
10/31 has EOM, but no weeklies in TT...


Screenshot 2024-10-10 at 13 52 33
Screenshot 2024-10-10 at 13 51 12

**Comment by Graeme22** [comment]
> Good point. I'm trying to find a date to test. 10/18 has AM settled and your lib is correctly ignoring it. 10/31 has EOM, but no weeklies in TT...

Correctly is subjective! What if you wanted to trade the AM settled?
Probably the way to handle this is to show the expiration type and not just the date when listing the expirations.

**Pull request merged**
